# Generated by Django 2.1.4 on 2018-12-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiloApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_number',
            field=models.IntegerField(null=True),
        ),
    ]
