# Generated by Django 2.1.4 on 2018-12-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiloApp', '0003_auto_20181221_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_number',
            field=models.IntegerField(default=40),
        ),
    ]
